# Generated by Django 4.2.7 on 2025-05-31 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rumahbelajar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GajiGuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=100)),
                ('gol', models.CharField(max_length=10)),
                ('no_rekening', models.CharField(max_length=30)),
                ('nominal_gaji', models.IntegerField()),
                ('bulan', models.CharField(max_length=20)),
                ('tahun', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pengeluaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.TextField()),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='RekapitulasiKeuangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.DateField()),
                ('total_pemasukan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_pengeluaran', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Tagihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.DateField()),
                ('spp', models.BooleanField(default=False)),
                ('daftar_ulang', models.BooleanField(default=False)),
                ('nomor_tagihan', models.CharField(blank=True, max_length=100, unique=True)),
                ('parent_tagihan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='keuangan.tagihan')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagihan_set', to='rumahbelajar.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='PembayaranSPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.CharField(choices=[('01', 'Januari'), ('02', 'Februari'), ('03', 'Maret'), ('04', 'April'), ('05', 'Mei'), ('06', 'Juni'), ('07', 'Juli'), ('08', 'Agustus'), ('09', 'September'), ('10', 'Oktober'), ('11', 'November'), ('12', 'Desember')], max_length=2)),
                ('jumlah_bayar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_bayar', models.CharField(choices=[('belum lunas', 'Belum Lunas'), ('lunas', 'Lunas')], default='belum lunas', max_length=20)),
                ('tanggal_bayar', models.DateField(blank=True, null=True)),
                ('bukti_pembayaran', models.ImageField(blank=True, null=True, upload_to='bukti_pembayaran/')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rumahbelajar.siswa')),
                ('tagihan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='keuangan.tagihan')),
            ],
        ),
        migrations.CreateModel(
            name='Pemasukan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jenis', models.CharField(choices=[('SPP', 'SPP'), ('CATERING', 'Catering'), ('DAFTAR_ULANG', 'Daftar Ulang'), ('LAINNYA', 'Lain-lain')], max_length=20)),
                ('siswa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rumahbelajar.siswa')),
            ],
        ),
    ]
