# Generated by Django 4.2.21 on 2025-06-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaranspp',
            name='tahun',
            field=models.IntegerField(default=2024),
        ),
    ]
