# Generated by Django 4.2.21 on 2025-06-15 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0002_pembayaranspp_tahun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembayaranspp',
            name='tahun',
        ),
    ]
