# Generated by Django 5.1.7 on 2025-04-30 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('no_telp', models.CharField(max_length=15)),
                ('mata_pelajaran', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JadwalLes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(max_length=10)),
                ('jam', models.TimeField()),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rumahbelajar.guru')),
            ],
        ),
        migrations.CreateModel(
            name='OrangTua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('no_telp', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rumahbelajar_orangtua', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(max_length=10)),
                ('orang_tua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rumahbelajar.orangtua')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rumahbelajar_siswa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Hadir', 'Hadir'), ('Tidak Hadir', 'Tidak Hadir')], max_length=20)),
                ('metode_absensi', models.CharField(choices=[('QR Code', 'QR Code'), ('Input Manual', 'Input Manual')], max_length=30)),
                ('guru', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rumahbelajar.guru')),
                ('siswa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rumahbelajar.siswa')),
            ],
        ),
    ]
