# Generated by Django 5.1.7 on 2025-05-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumahbelajar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('mata_pelajaran', models.CharField(max_length=100)),
            ],
        ),
    ]
