# Generated by Django 5.1.7 on 2025-05-05 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumahbelajar', '0002_kelas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kelas',
            old_name='nama',
            new_name='nama_kelas',
        ),
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelajaran', models.CharField(max_length=100)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rumahbelajar.kelas')),
            ],
        ),
    ]
