# Generated by Django 5.1.7 on 2025-05-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumahbelajar', '0003_rename_nama_kelas_nama_kelas_matapelajaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwalles',
            name='jam',
            field=models.CharField(max_length=20),
        ),
    ]
