# Generated by Django 5.1.7 on 2025-05-05 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rumahbelajar', '0004_alter_jadwalles_jam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kelas',
            old_name='nama_kelas',
            new_name='nama',
        ),
    ]
